# GitHub Pages configuration
permalink: pretty

# Set default page
defaults:
  - scope:
      path: ""
    values:
      layout: default

# Custom 404 page
404: /404.html

# Site configuration
title: "Waondo Community Church"
description: "Supporting orphaned and vulnerable children on Mfangano Island, Kenya through education, healthcare, and community programs at Rays Of Hope Christian Centre."
baseurl: ""
url: ""

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
